#!/bin/bash

source ~/bin/reminder/reminder.properties

if [ -s $REMINDERS_PATH ]; then
    IFS=$'\n'
    ITEMS=( $($AWK_REMINDER $REMINDERS_PATH) )
    RESP=( $(GTK_THEME="Yaru-colors/Yaru-Grey-dark" yad --display=":0.0" --list --width="1850" --height="750" --title="Reminders" \
    --button='<span color="orange">Exit</span>:1' --button='<span color="khaki">Show Task</span>:0' \
    --button='<span color="deepskyblue">Show Preview</span>:2' --button='<span color="tomato">Delete Reminder</span>:4' \
    --multiple --separator="::" --print-column="0" \
    --column="ID" --column="Task ID" --column="Description"  --column="Preview URL" --column="Repository" --column="Priority" \
    ${ITEMS[@]}) )
    CODE=$?
    unset IFS
    case $CODE in
        0)
            data=`echo ${RESP[@]} | awk 'BEGIN{ RS = ":: " ; FS = "::" } {print $2"::"$3"::"$5}'`
            IFS=$'\n'
            for each in $data; do
                task=`echo $each | awk -F "::" '{print $1}' | grep -Eo '(www|http|https).*(\.[a-z]{2,4}[^<]*)'`
                $GCHROME $task &> /dev/null &
            done
            unset IFS
            ;;
        2)
            prev=`echo ${RESP[@]} | awk 'BEGIN{ RS = ":: "; FS = "::" } {print $4}' | grep -Eo '(www|http|https).*(\.[a-z]{2,4}[^<]*)'`
            for each in $prev; do
                $GCHROME $each &> /dev/null &
            done
            ;;
        4)
            data=`echo ${RESP[@]} | awk 'BEGIN{ RS = ":: " ; FS = "::" } {print $1}'`
            for del_id in $aux; do
                $REMINDER -del $del_id
            done
            ;;
        *)
            exit
            ;;
    esac
fi
